export const backupData = [
  {
    id: 1,
    name: "Suplementos",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/suplementos",
    children: [
      {
        id: 2,
        name: "Aminoácidos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos",
        children: [
          {
            id: 3,
            name: "Arginina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/arginina",
            children: [],
            Title: "Arginina",
            MetaTagDescription: "",
          },
          {
            id: 4,
            name: "BCAA",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/bcaa",
            children: [],
            Title: "BCAA",
            MetaTagDescription: "",
          },
          {
            id: 5,
            name: "Creatina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/creatina",
            children: [],
            Title: "Creatina",
            MetaTagDescription: "",
          },
          {
            id: 6,
            name: "Glutamina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/glutamina",
            children: [],
            Title: "Glutamina",
            MetaTagDescription: "",
          },
          {
            id: 7,
            name: "Isoleucina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/isoleucina",
            children: [],
            Title: "Isoleucina",
            MetaTagDescription: "",
          },
          {
            id: 8,
            name: "L-Carnitina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/l-carnitina",
            children: [],
            Title: "L-Carnitina",
            MetaTagDescription: "",
          },
          {
            id: 9,
            name: "Leucina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/leucina",
            children: [],
            Title: "Leucina",
            MetaTagDescription: "",
          },
          {
            id: 10,
            name: "Taurina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/taurina",
            children: [],
            Title: "Taurina",
            MetaTagDescription: "",
          },
          {
            id: 11,
            name: "Valina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/aminoacidos/valina",
            children: [],
            Title: "Valina",
            MetaTagDescription: "",
          },
        ],
        Title: "Aminoácidos",
        MetaTagDescription: "",
      },
      {
        id: 12,
        name: "Carboidratos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos",
        children: [
          {
            id: 13,
            name: "Dextrose",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/dextrose",
            children: [],
            Title: "Dextrose",
            MetaTagDescription: "",
          },
          {
            id: 14,
            name: "Hipercalórico",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/hipercalorico",
            children: [],
            Title: "Hipercalórico",
            MetaTagDescription: "",
          },
          {
            id: 15,
            name: "Maltodextrina",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/maltodextrina",
            children: [],
            Title: "Maltodextrina",
            MetaTagDescription: "",
          },
          {
            id: 16,
            name: "Palatinose",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/palatinose",
            children: [],
            Title: "Palatinose",
            MetaTagDescription: "",
          },
          {
            id: 17,
            name: "Ribose",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/ribose",
            children: [],
            Title: "Ribose",
            MetaTagDescription: "",
          },
          {
            id: 18,
            name: "Waxy Maize",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/carboidratos/waxy-maize",
            children: [],
            Title: "Waxy Maize",
            MetaTagDescription: "",
          },
        ],
        Title: "Carboidratos",
        MetaTagDescription: "",
      },
      {
        id: 19,
        name: "Energia e Resistência",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/energia-e-resistencia",
        children: [
          {
            id: 20,
            name: "Barra energética",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/energia-e-resistencia/barra-energetica",
            children: [],
            Title: "Barra energética",
            MetaTagDescription: "",
          },
          {
            id: 21,
            name: "Emagrecedores",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/energia-e-resistencia/emagrecedores",
            children: [],
            Title: "Emagrecedores",
            MetaTagDescription: "",
          },
          {
            id: 22,
            name: "Pré-treino",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/energia-e-resistencia/pre-treino",
            children: [],
            Title: "Pré-treino",
            MetaTagDescription: "",
          },
        ],
        Title: "Energia e Resistência",
        MetaTagDescription: "",
      },
      {
        id: 23,
        name: "Proteicos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteicos",
        children: [
          {
            id: 24,
            name: "Barras",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteicos/barras",
            children: [],
            Title: "Barras",
            MetaTagDescription: "",
          },
          {
            id: 25,
            name: "Doces",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteicos/doces",
            children: [],
            Title: "Doces",
            MetaTagDescription: "",
          },
          {
            id: 26,
            name: "Misturas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteicos/misturas",
            children: [],
            Title: "Misturas",
            MetaTagDescription: "",
          },
          {
            id: 27,
            name: "Sopas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteicos/sopas",
            children: [],
            Title: "Sopas",
            MetaTagDescription: "",
          },
        ],
        Title: "Proteicos",
        MetaTagDescription: "",
      },
      {
        id: 28,
        name: "Proteína",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina",
        children: [
          {
            id: 29,
            name: "Proteína Vegetal",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina/proteina-vegetal",
            children: [],
            Title: "Proteína Vegetal",
            MetaTagDescription: "",
          },
          {
            id: 30,
            name: "Proteína da Carne",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina/proteina-da-carne",
            children: [],
            Title: "Proteína da Carne",
            MetaTagDescription: "",
          },
          {
            id: 31,
            name: "Proteína de Colágeno",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina/proteina-de-colageno",
            children: [],
            Title: "Proteína de Colágeno",
            MetaTagDescription: "",
          },
          {
            id: 32,
            name: "Proteína do Leite",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina/proteina-do-leite",
            children: [],
            Title: "Proteína do Leite",
            MetaTagDescription: "",
          },
          {
            id: 33,
            name: "Proteína do Ovo",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/proteina/proteina-do-ovo",
            children: [],
            Title: "Proteína do Ovo",
            MetaTagDescription: "",
          },
        ],
        Title: "Proteína",
        MetaTagDescription: "",
      },
      {
        id: 34,
        name: "Vitaminas e Saúde",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude",
        children: [
          {
            id: 35,
            name: "Colágenos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude/colagenos",
            children: [],
            Title: "Colágenos",
            MetaTagDescription: "",
          },
          {
            id: 36,
            name: "Vitaminas A a Z",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude/vitaminas-a-a-z",
            children: [],
            Title: "Vitaminas A a Z",
            MetaTagDescription: "",
          },
          {
            id: 37,
            name: "Multivitamínicos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude/multivitaminicos",
            children: [],
            Title: "Multivitamínicos",
            MetaTagDescription: "",
          },
          {
            id: 38,
            name: "Fitoterápicos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude/fitoterapicos",
            children: [],
            Title: "Fitoterápicos",
            MetaTagDescription: "",
          },
          {
            id: 39,
            name: "Ômegas e Ácidos Graxos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/suplementos/vitaminas-e-saude/omegas-e-acidos-graxos",
            children: [],
            Title: "Ômegas e Ácidos Graxos",
            MetaTagDescription: "",
          },
        ],
        Title: "Vitaminas e Saúde",
        MetaTagDescription: "",
      },
    ],
    Title: "Suplementos",
    MetaTagDescription: "",
  },
  {
    id: 40,
    name: "Departamento Teste",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/departamento-teste",
    children: [
      {
        id: 41,
        name: "Teste - Categoria Simples",
        hasChildren: false,
        url: "https://emporiodadario.vtexcommercestable.com.br/departamento-teste/teste---categoria-simples",
        children: [],
        Title: "Teste - Categoria Simples",
        MetaTagDescription: "Teste - Categoria Simples",
      },
      {
        id: 42,
        name: "Teste - Categoria Variação",
        hasChildren: false,
        url: "https://emporiodadario.vtexcommercestable.com.br/departamento-teste/teste---categoria-variacao",
        children: [],
        Title: "Teste - Categoria Variação",
        MetaTagDescription: "Teste - Categoria Variação",
      },
    ],
    Title: "Departamento Teste",
    MetaTagDescription: "Departamento Teste",
  },
  {
    id: 43,
    name: "Frutas e Oleaginosas",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas",
    children: [
      {
        id: 44,
        name: "Oleaginosas",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas",
        children: [
          {
            id: 46,
            name: "Amêndoas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/amendoas",
            children: [],
            Title: "Amêndoas- Empório Dadário",
            MetaTagDescription: "Amêndoas- Empório Dadário",
          },
          {
            id: 47,
            name: "Castanhas do Pará",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/castanhas-do-para",
            children: [],
            Title: "Castanhas do Pará",
            MetaTagDescription: "Castanhas do Pará",
          },
          {
            id: 48,
            name: "Nozes",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/nozes",
            children: [],
            Title: "Nozes",
            MetaTagDescription: "Nozes",
          },
          {
            id: 49,
            name: "Avelã",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/avela",
            children: [],
            Title: "Avelã",
            MetaTagDescription: "Avelã",
          },
          {
            id: 50,
            name: "Pistache e Macadâmia",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/pistache-e-macadamia",
            children: [],
            Title: "Pistache e Macadâmia",
            MetaTagDescription: "Pistache e Macadâmia",
          },
          {
            id: 51,
            name: "Castanhas de Cajú",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/castanhas-de-caju",
            children: [],
            Title: "Castanhas de Cajú",
            MetaTagDescription: "Castanhas de Cajú",
          },
          {
            id: 52,
            name: "Mix de Oleaginosas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/mix-de-oleaginosas",
            children: [],
            Title: "Mix de Oleaginosas",
            MetaTagDescription: "Mix de Oleaginosas",
          },
          {
            id: 53,
            name: "Amendoins",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/oleaginosas/amendoins",
            children: [],
            Title: "Amendoins",
            MetaTagDescription: "Amendoins",
          },
        ],
        Title: "Oleaginosas- Empório Dadário",
        MetaTagDescription: "Oleaginosas- Empório Dadário",
      },
      {
        id: 45,
        name: "Frutas",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/frutas",
        children: [
          {
            id: 54,
            name: "Frutas Glaceadas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/frutas/frutas-glaceadas",
            children: [],
            Title: "Frutas Glaceadas",
            MetaTagDescription: "Frutas Glaceadas",
          },
          {
            id: 55,
            name: "Frutas Secas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/frutas/frutas-secas",
            children: [],
            Title: "Frutas Secas",
            MetaTagDescription: "Frutas Secas",
          },
          {
            id: 56,
            name: "Frutas Cristalizadas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/frutas-e-oleaginosas/frutas/frutas-cristalizadas",
            children: [],
            Title: "Frutas Cristalizadas",
            MetaTagDescription: "Frutas Cristalizadas",
          },
        ],
        Title: "Frutas - Empório Dadário",
        MetaTagDescription: "Frutas - Empório Dadário",
      },
    ],
    Title: "Frutas e Oleaginosas- Empório Dadário",
    MetaTagDescription: "Frutas e Oleaginosas- Empório Dadário",
  },
  {
    id: 57,
    name: "Mercearia",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/mercearia",
    children: [
      {
        id: 58,
        name: "Temperos e Especiarias",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias",
        children: [
          {
            id: 74,
            name: "Temperos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/temperos",
            children: [],
            Title: "Temperos",
            MetaTagDescription: "Temperos",
          },
          {
            id: 75,
            name: "Especiarias",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/especiarias",
            children: [],
            Title: "Especiarias",
            MetaTagDescription: "Especiarias",
          },
          {
            id: 76,
            name: "Condimentos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/condimentos",
            children: [],
            Title: "Condimentos",
            MetaTagDescription: "Condimentos",
          },
          {
            id: 77,
            name: "Vinagres",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/vinagres",
            children: [],
            Title: "Vinagres",
            MetaTagDescription: "Vinagres",
          },
          {
            id: 78,
            name: "Azeite e Óleos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/azeite-e-oleos",
            children: [],
            Title: "Azeite e Óleos",
            MetaTagDescription: "Azeite e Óleos",
          },
          {
            id: 79,
            name: "Molhos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/temperos-e-especiarias/molhos",
            children: [],
            Title: "Molhos",
            MetaTagDescription: "Molhos",
          },
        ],
        Title: "Temperos e Especiarias",
        MetaTagDescription: "Temperos e Especiarias",
      },
      {
        id: 59,
        name: "Petiscos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos",
        children: [
          {
            id: 66,
            name: "Aperitivos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/aperitivos",
            children: [],
            Title: "Aperitivos",
            MetaTagDescription: "Aperitivos",
          },
          {
            id: 67,
            name: "Amendoins",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/amendoins",
            children: [],
            Title: "Amendoins",
            MetaTagDescription: "Amendoins",
          },
          {
            id: 68,
            name: "Barrinhas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/barrinhas",
            children: [],
            Title: "Barrinhas",
            MetaTagDescription: "Barrinhas",
          },
          {
            id: 69,
            name: "Biscoito e Cookies",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/biscoito-e-cookies",
            children: [],
            Title: "Biscoito e Cookies",
            MetaTagDescription: "Biscoito e Cookies",
          },
          {
            id: 70,
            name: "Chips",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/chips",
            children: [],
            Title: "Chips",
            MetaTagDescription: "Chips",
          },
          {
            id: 71,
            name: "Chocolates",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/chocolates",
            children: [],
            Title: "Chocolates",
            MetaTagDescription: "Chocolates",
          },
          {
            id: 72,
            name: "Doces",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/doces",
            children: [],
            Title: "Doces",
            MetaTagDescription: "Doces",
          },
          {
            id: 73,
            name: "Snacks",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/petiscos/snacks",
            children: [],
            Title: "Snacks",
            MetaTagDescription: "Snacks",
          },
        ],
        Title: "Petiscos",
        MetaTagDescription: "Petiscos",
      },
      {
        id: 60,
        name: "Ervas e Chás",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas",
        children: [
          {
            id: 61,
            name: "Mix",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas/mix",
            children: [],
            Title: "Mix",
            MetaTagDescription: "Mix",
          },
          {
            id: 62,
            name: "Em pó",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas/em-po",
            children: [],
            Title: "Em pó",
            MetaTagDescription: "Em pó",
          },
          {
            id: 63,
            name: "Sachês",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas/saches",
            children: [],
            Title: "Sachês",
            MetaTagDescription: "Sachês",
          },
          {
            id: 64,
            name: "Solúveis",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas/soluveis",
            children: [],
            Title: "Solúveis",
            MetaTagDescription: "Solúveis",
          },
          {
            id: 65,
            name: "Folhas e Flores",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/mercearia/ervas-e-chas/folhas-e-flores",
            children: [],
            Title: "Folhas e Flores",
            MetaTagDescription: "Folhas e Flores",
          },
        ],
        Title: "Ervas e Chás",
        MetaTagDescription: "Ervas e Chás",
      },
    ],
    Title: "Mercearia",
    MetaTagDescription: "Mercearia",
  },
  {
    id: 80,
    name: "Produtos Naturais",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais",
    children: [
      {
        id: 81,
        name: "Farinhas e Farelos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/farinhas-e-farelos",
        children: [
          {
            id: 92,
            name: "Farinha",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/farinhas-e-farelos/farinha",
            children: [],
            Title: "Farinha",
            MetaTagDescription: "Farinha",
          },
          {
            id: 93,
            name: "Farelo",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/farinhas-e-farelos/farelo",
            children: [],
            Title: "Farelo",
            MetaTagDescription: "Farelo",
          },
          {
            id: 94,
            name: "Produtos em pó",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/farinhas-e-farelos/produtos-em-po",
            children: [],
            Title: "Produtos em pó",
            MetaTagDescription: "Produtos em pó",
          },
        ],
        Title: "Farinhas e Farelos",
        MetaTagDescription: "Farinhas e Farelos",
      },
      {
        id: 82,
        name: "Açucar e Adoçantes",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/acucar-e-adocantes",
        children: [
          {
            id: 86,
            name: "Açuçares",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/acucar-e-adocantes/acucares",
            children: [],
            Title: "Açuçares",
            MetaTagDescription: "Açuçares",
          },
          {
            id: 87,
            name: "Adoçantes",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/acucar-e-adocantes/adocantes",
            children: [],
            Title: "Adoçantes",
            MetaTagDescription: "Adoçantes",
          },
          {
            id: 88,
            name: "Mel e Derivados",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/acucar-e-adocantes/mel-e-derivados",
            children: [],
            Title: "Mel e Derivados",
            MetaTagDescription: "Mel e Derivados",
          },
        ],
        Title: "Açucar e Adoçantes",
        MetaTagDescription: "Açucar e Adoçantes",
      },
      {
        id: 83,
        name: "Cereais",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/cereais",
        children: [
          {
            id: 89,
            name: "Aveia",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/cereais/aveia",
            children: [],
            Title: "Aveia",
            MetaTagDescription: "Aveia",
          },
          {
            id: 90,
            name: "Cereal Matinal",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/cereais/cereal-matinal",
            children: [],
            Title: "Cereal Matinal",
            MetaTagDescription: "Cereal Matinal",
          },
          {
            id: 91,
            name: "Granolas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/cereais/granolas",
            children: [],
            Title: "Granolas",
            MetaTagDescription: "Granolas",
          },
        ],
        Title: "Cereais",
        MetaTagDescription: "Cereais",
      },
      {
        id: 84,
        name: "Grãos e Sementes",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/graos-e-sementes",
        children: [
          {
            id: 95,
            name: "Grãos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/graos-e-sementes/graos",
            children: [],
            Title: "Grãos",
            MetaTagDescription: "Grãos",
          },
          {
            id: 96,
            name: "Sementes",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/graos-e-sementes/sementes",
            children: [],
            Title: "Sementes",
            MetaTagDescription: "Sementes",
          },
        ],
        Title: "Grãos e Sementes",
        MetaTagDescription: "Grãos e Sementes",
      },
      {
        id: 85,
        name: "Produtos Integrais",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/produtos-integrais",
        children: [
          {
            id: 101,
            name: "Massas",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/produtos-naturais/produtos-integrais/massas",
            children: [],
            Title: "Massas-Empório Dadário",
            MetaTagDescription: "",
          },
        ],
        Title: "Produtos Integrais",
        MetaTagDescription: "Produtos Integrais",
      },
    ],
    Title: "Produtos Naturais",
    MetaTagDescription: "Produtos Naturais",
  },
  {
    id: 97,
    name: "Encapsulados e Fitoterápicos",
    hasChildren: true,
    url: "https://emporiodadario.vtexcommercestable.com.br/encapsulados-e-fitoterapicos",
    children: [
      {
        id: 98,
        name: "Fitoterápicos",
        hasChildren: true,
        url: "https://emporiodadario.vtexcommercestable.com.br/encapsulados-e-fitoterapicos/fitoterapicos",
        children: [
          {
            id: 99,
            name: "Óleos",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/encapsulados-e-fitoterapicos/fitoterapicos/oleos",
            children: [],
            Title: "Óleos",
            MetaTagDescription: "Óleos",
          },
          {
            id: 100,
            name: "Florais",
            hasChildren: false,
            url: "https://emporiodadario.vtexcommercestable.com.br/encapsulados-e-fitoterapicos/fitoterapicos/florais",
            children: [],
            Title: "Florais",
            MetaTagDescription: "Florais",
          },
        ],
        Title: "Fitoterápicos",
        MetaTagDescription: "Fitoterápicos",
      },
    ],
    Title: "Encapsulados e Fitoterápicos",
    MetaTagDescription: "Encapsulados e Fitoterápicos",
  },
];
